---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: coldmania
description: "Coldmania OS: Mijn eigen Linux distributie met Hyprland."
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 44

modules:
  - type: dnf
    install:
      packages:
        - hyprland
        - waybar
        - wofi
        - alacritty
        - neofetch

  - type: flatpak
    install:
      flatpaks:
        - org.mozilla.firefox
        - com.github.tchx84.Flatseal
