name: bluebuild
on:
  push:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - recipes/recipe.yml
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Custom Image
        uses: blue-build/github-action@v1.11
        with:
          recipe: ${{ matrix.recipe }}
          skip-if-available: 0
