name: Build Coldmania OS

on:
  schedule:
    - cron: "0 0 * * *" # Build daily at midnight
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab

jobs:
  bluebuild:
    name: Build Coldmania
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Coldmania Image
        uses: blue-build/github-action@v1.12
        with:
          recipe: recipe.yml
          registry_namespace: ${{ github.repository_owner }}
